export let data = [
   {
      id: 0,
      category: 'top',
      brand: '모이프',
      productName: '[SS23]WIDE DRAWSTRING BLOUSON / PAJAMA STRIPE',
      price: 238000,
      remainingCount: 10,
      filePath: '../images/top/',
      fileName: 'top_00',
      fileExtension: '.jpg',
   },
   {
      id: 1,
      category: 'top',
      brand: '토마스모어',
      productName: 'TD5-SH07 페이퍼셔츠 (9 Color)',
      price: 59700,
      remainingCount: 12,
      filePath: '../images/top/',
      fileName: 'top_01',
      fileExtension: '.jpg',
   },
   {
      id: 2,
      category: 'top',
      brand: '르아브',
      productName: '[단독]_라이크리넨 셔츠 (15COLOR)',
      price: 69700,
      remainingCount: 13,
      filePath: '../images/top/',
      fileName: 'top_02',
      fileExtension: '.jpg',
   },
   {
      id: 3,
      category: 'top',
      brand: '어나더오피스',
      productName: '23SS Writer Shirt (Almond Milk)',
      price: 96000,
      remainingCount: 9,
      filePath: '../images/top/',
      fileName: 'top_03',
      fileExtension: '.jpg',
   },
   {
      id: 4,
      category: 'top',
      brand: '포터리',
      productName: 'Comfort Shirt (Sax)',
      price: 189000,
      remainingCount: 12,
      filePath: '../images/top/',
      fileName: 'top_04',
      fileExtension: '.jpg',
   },
   {
      id: 5,
      category: 'top',
      brand: '포터리',
      productName: 'Button Down Shirt_Sax',
      price: 189000,
      remainingCount: 9,
      filePath: '../images/top/',
      fileName: 'top_05',
      fileExtension: '.jpg',
   },
   {
      id: 6,
      category: 'top',
      brand: '유스',
      productName: 'H/S Logo T-shirt (M) Black',
      price: 63000,
      remainingCount: 7,
      filePath: '../images/top/',
      fileName: 'top_06',
      fileExtension: '.jpg',
   },
   {
      id: 7,
      category: 'top',
      brand: '탄즈탄즈탄즈',
      productName: 'TZA2103-KH',
      price: 170000,
      remainingCount: 6,
      filePath: '../images/top/',
      fileName: 'top_07',
      fileExtension: '.jpg',
   },
   {
      id: 8,
      category: 'top',
      brand: '포터리',
      productName: 'Short Sleeve Comfort Shirt_12 Color',
      price: 159000,
      remainingCount: 11,
      filePath: '../images/top/',
      fileName: 'top_08',
      fileExtension: '.jpg',
   },
   {
      id: 9,
      category: 'top',
      brand: '네이더스',
      productName: 'ENGINEER L/S SHIRT (GREY)',
      price: 158000,
      remainingCount: 3,
      filePath: '../images/top/',
      fileName: 'top_09',
      fileExtension: '.jpg',
   },
   {
      id: 10,
      category: 'bottoms',
      brand: '어나더오피스',
      productName: '23SS M51 Field Pants (Olive Drab)',
      price: 168000,
      remainingCount: 12,
      filePath: '../images/bottoms/',
      fileName: 'bottoms_00',
      fileExtension: '.jpg',
   },
   {
      id: 11,
      category: 'bottoms',
      brand: '어나더오피스',
      productName: '23SS Santiago Slacks Standard (Black)',
      price: 156000,
      remainingCount: 11,
      filePath: '../images/bottoms/',
      fileName: 'bottoms_01',
      fileExtension: '.jpg',
   },
   {
      id: 12,
      category: 'bottoms',
      brand: '슬릭앤이지',
      productName: 'Officer Chino Pants 오피서 치노 팬츠',
      price: 143650,
      remainingCount: 8,
      filePath: '../images/bottoms/',
      fileName: 'bottoms_02',
      fileExtension: '.png',
   },
   {
      id: 13,
      category: 'bottoms',
      brand: '슬릭앤이지',
      productName: 'Andy Pants Selvedge Blue 앤디 팬츠 셀비지 블루',
      price: 246050,
      remainingCount: 6,
      filePath: '../images/bottoms/',
      fileName: 'bottoms_03',
      fileExtension: '.png',
   },
   {
      id: 14,
      category: 'bottoms',
      brand: '이얼즈어고',
      productName: 'OVERLAP TWO TUCK WIDE PANTS - COTTON LIGHT GREY',
      price: 228000,
      remainingCount: 7,
      filePath: '../images/bottoms/',
      fileName: 'bottoms_04',
      fileExtension: '.jpg',
   },
   {
      id: 15,
      category: 'bottoms',
      brand: '유스',
      productName: 'Structured Wide Denim Pants Light Blue',
      price: 208000,
      remainingCount: 11,
      filePath: '../images/bottoms/',
      fileName: 'bottoms_05',
      fileExtension: '.jpg',
   },
   {
      id: 16,
      category: 'bottoms',
      brand: '티엔알',
      productName: '[TNR] Black washed denim',
      price: 169000,
      remainingCount: 5,
      filePath: '../images/bottoms/',
      fileName: 'bottoms_06',
      fileExtension: '.jpg',
   },
   {
      id: 17,
      category: 'bottoms',
      brand: '스테디 에브리웨어',
      productName: 'Relaxed Denim Pants (Light Blue)',
      price: 159000,
      remainingCount: 7,
      filePath: '../images/bottoms/',
      fileName: 'bottoms_07',
      fileExtension: '.jpg',
   },
   {
      id: 18,
      category: 'bottoms',
      brand: '고요웨어',
      productName: 'ADVANCE VENTIL PANTS (BLACK)',
      price: 158000,
      remainingCount: 8,
      filePath: '../images/bottoms/',
      fileName: 'bottoms_08',
      fileExtension: '.jpg',
   },
   {
      id: 19,
      category: 'bottoms',
      brand: '어나더오피스',
      productName: '23SS Santiago Slacks Standard (Graphite)',
      price: 156000,
      remainingCount: 13,
      filePath: '../images/bottoms/',
      fileName: 'bottoms_09',
      fileExtension: '.jpg',
   },
   {
      id: 20,
      category: 'outerwear',
      brand: '바라쿠타',
      productName: '바라쿠타 G9 헤링턴 자켓 - 블랙 (BRCPS0001BCNY1 100)',
      price: 272000,
      remainingCount: 4,
      filePath: '../images/outerwear/',
      fileName: 'outerwear_00',
      fileExtension: '.jpg',
   },
   {
      id: 21,
      category: 'outerwear',
      brand: '어나더오피스',
      productName: '23SS Santiago Blazer (Graphite)',
      price: 278000,
      remainingCount: 6,
      filePath: '../images/outerwear/',
      fileName: 'outerwear_01',
      fileExtension: '.jpg',
   },
   {
      id: 22,
      category: 'outerwear',
      brand: '부기홀리데이',
      productName: '[5월12일 순차발송]_09 CHAMBRAY WORK SHIRT (blue)',
      price: 112100,
      remainingCount: 4,
      filePath: '../images/outerwear/',
      fileName: 'outerwear_02',
      fileExtension: '.jpg',
   },
   {
      id: 23,
      category: 'outerwear',
      brand: '모이프',
      productName: '[SS23]UNIFORM JACKET / BLACK NC',
      price: 297000,
      remainingCount: 9,
      filePath: '../images/outerwear/',
      fileName: 'outerwear_03',
      fileExtension: '.jpg',
   },
   {
      id: 24,
      category: 'outerwear',
      brand: '어나더오피스',
      productName: '23SS Santiago Blazer (Heather Gray)',
      price: 278000,
      remainingCount: 7,
      filePath: '../images/outerwear/',
      fileName: 'outerwear_04',
      fileExtension: '.jpg',
   },
   {
      id: 25,
      category: 'outerwear',
      brand: '벨리에',
      productName: '다이에그널 블루종 자켓 - 레이븐 블랙',
      price: 239000,
      remainingCount: 5,
      filePath: '../images/outerwear/',
      fileName: 'outerwear_05',
      fileExtension: '.jpg',
   },
   {
      id: 26,
      category: 'outerwear',
      brand: '모이프',
      productName: '[SS23]ALL-TERRAIN PARKA / ECRU NC',
      price: 367000,
      remainingCount: 4,
      filePath: '../images/outerwear/',
      fileName: 'outerwear_06',
      fileExtension: '.jpg',
   },
   {
      id: 27,
      category: 'outerwear',
      brand: '포터리',
      productName: 'Wool Sports Jacket_Dark Gray',
      price: 359000,
      remainingCount: 8,
      filePath: '../images/outerwear/',
      fileName: 'outerwear_07',
      fileExtension: '.jpg',
   },
   {
      id: 28,
      category: 'outerwear',
      brand: '토마스모어',
      productName: 'TD5-JP01 탱커 블루종-블랙',
      price: 107000,
      remainingCount: 10,
      filePath: '../images/outerwear/',
      fileName: 'outerwear_08',
      fileExtension: '.jpg',
   },
   {
      id: 29,
      category: 'outerwear',
      brand: '24/7 시리즈',
      productName: 'COMFORT SET-UP OVER JACKET MELANGE GRAY (247)',
      price: 132050,
      remainingCount: 11,
      filePath: '../images/outerwear/',
      fileName: 'outerwear_09',
      fileExtension: '.jpg',
   },
];
/* 
[형식] 아이디, 분류, 브랜드, 제품명, 가격, 남은수량, 파일경로, 파일명, 파일확장자
[출처] 29cm, https://shop.29cm.co.kr/ (2023-04-28)
*/
